on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: setup-gradle
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew assemble
      - name: test
        run: ./gradlew check