name: build
on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: setup-gradle
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew assemble
      - name: save-build-artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: '*/build'
          retention-days: 1
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: get-build-artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
      - name: setup-gradle
        run: chmod +x ./gradlew
      - name: test
        run: ./gradlew check