name: build
on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - uses: actions/cache@v3
        with:
          path: '*/build'
          key: build-${{ github.sha }}
      - name: build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: '*/build/libs/*.jar'
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - uses: actions/cache@v3
        with:
          path: '*/build'
          key: build-${{ github.sha }}
      - name: test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check
