name: publish
on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.1.2
        with:
          ref: ${{ github.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          check-name: build
          allowed-conclusions: success
          wait-interval: 10
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - uses: actions/cache@v3
        with:
          path: '*/build'
          key: build-${{ github.sha }}
      - uses: ncipollo/release-action@v1
        with:
          artifacts: '*/build/libs/*.jar'
          prerelease: ${{ contains(github.ref_name, 'beta') || contains(github.ref_name, 'alpha') }}
      - name: maven-publish
        uses: gradle/gradle-build-action@v2
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_PGP_KEY: ${{ secrets.SONATYPE_PGP_KEY }}
          SONATYPE_PGP_PASSWORD: ${{ secrets.SONATYPE_PGP_PASSWORD }}
        with:
          arguments: publishToSonatype closeSonatypeStagingRepository # TODO: Change this to closeAndRelease after the first testing
